### ISSUE TITLE
Programa 2022

### ISSUE THREAD

**Issue by TuQmano** [TuQmano/geo_utdt#4]
## Rearmar contenido en función de propuestas de contenidos en conjunto con [materias de datos](https://docs.google.com/document/d/1ssXYdjnVH5clH-NJ_htyd04tdT-flMRaI_N_rDAO5fI/edit).

**Comment by TuQmano** [comment]
# Instrumentos de Análisis Urbano 2

**Clase 1: Presentación** 
Configuración de herramientas y puesta en marcha (R, RStudio, Slack, .git / GitHub)

**Clase 2: Introducción** (Pensar solo como repaso corto de contenido de materia previa?)
R + RStudio.  Organización del flujo de trabajo (.`Rproj`, y `git`). R `base ` vs _Tidyverse_.  Reproducibilidad y Comunicación (`.R` y `Rmd`)

**Clase 3: Domar los datos I** 
Los principales paquetes y sus verbos para:
leer datos (`readr`, `heaven`, `readxl`, `googlesheets4`, etc)
limpiar datos (`tidyr`, `janitor`, `tibble`)
+`dplyr` (clase anterior) - repaso de CD1 y funciones auxiliares `dplyr` (`cotnains`() ,etc.)

Herramientas auxiliares para mejorar el flujo del código:
la pipa de `magrittr` (`%>%`) para encadenar y `glue` para facilitar la concatenación.

**Clase 4: Domar los datos II**
Ampliando la caja de herramientas:
`lubridate` para trabajar el tiempo
`forcats` para datos categóricos (factors)
`stringr` para datos de texto
 

**Clase 5: Programación (intro)**
No repetirse uno mismo
Escribir funciones
Programación funcional (Introducción a `purrr `)

**Clase6: Domar los datos III** - Trabajar con geo data:
`sf`
`rmapshaper`
`geoAr`

**Clase 7: Data Viz I** - _La Gramática de los Gráficos_
Introducción a `ggplot2`

**Clase 8: Data Viz II**
Las muchas capas de ggplot2
Extensiones: `patchwork`, `cowplot `, entre otros.

**Clase 9:  ????**

**Clase 10: Data Viz III**
Distintas formas de representar información geográfica:
`geom_sf`(): para mapas estáticos `mapsf`
leaflet: para mapas interactivos
`geofacet`: para grillas como si fueran mapas
`tilemaps`: cuando el área no importa


**Manual de clase**  https://tuqmano.github.io/geo_utdt/

**Comment by pablotis** [comment]
# Instrumentos de Análisis Urbano 2


**Clase 1: Presentación** 
Configuración y presentación de herramientas de trabajo para la puesta en marcha (R, RStudio, Slack, .git / GitHub)
--> _.git / Github sería más bien presentación e introducción, pensando en que va a ser contenido nuevo para muchxs_


**Clase 2: Introducción** (Pensar solo como repaso corto de contenido de materia previa?)
R + RStudio.  Organización del flujo de trabajo (.`Rproj`, y `git`). Reproducibilidad y Comunicación (`.R` y `Rmd`)
--> _No lo pensaría como repaso, entiendo que no han visto aún de forma integral el armado de un proyecto, más allá de alguna de sus partes_
--> _Sacaría R base, creo que confundiría más si no tenemos algo concreto en el que lo vamos a necesitar, siendo que es duro y tomaría una clase entera, me parece_


**Clase 3: Domar los datos I** 
Los principales paquetes y sus verbos para:
leer datos (`readr`, `heaven`, `readxl`, `googlesheets4`, etc)
limpiar datos (`tidyr`, `janitor`, `tibble`)
+`dplyr` (clase anterior) - repaso de CD1 y funciones auxiliares `dplyr` (`cotnains`() ,etc.)

Herramientas auxiliares para mejorar el flujo del código:
la pipa de `magrittr` (`%>%`) para encadenar y `glue` para facilitar la concatenación.

**Clase 4: Domar los datos II**
Ampliando la caja de herramientas:
`lubridate` para trabajar el tiempo
`forcats` para datos categóricos (factors)
`stringr` para datos de texto
 

**Clase 5: Programación (intro)**
No repetirse uno mismo
Escribir funciones
Programación funcional (Introducción a `purrr `)

**Clase6: Domar los datos III** - Trabajar con geo data:
`sf`
`rmapshaper`
`geoAr`

**Clase 7: Data Viz I** - _La Gramática de los Gráficos_
Introducción a `ggplot2`

**Clase 8: Data Viz II**
Las muchas capas de ggplot2
Extensiones: `patchwork`, `cowplot `, entre otros.

**Clase 9:  ????**
- Podemos usar esta clase libre (en el orden que sea) para poner en práctica lo visto hasta x momento. O dejarla para el final para espacio de puesta en común sobre proyectos / avance grupal / Ejercitación / algo por el estilo.  

**Clase 10: Data Viz III**
Distintas formas de representar información geográfica:
`geom_sf`(): para mapas estáticos `mapsf`
leaflet: para mapas interactivos
`geofacet`: para grillas como si fueran mapas
`tilemaps`: cuando el área no importa


**Manual de clase**  https://tuqmano.github.io/geo_utdt/

**Comment by pablotis** [comment]
# Instrumentos de Análisis Urbano 2



## Clase 1: Presentación

#### Configuración y presentación de herramientas de trabajo para la puesta en marcha.
- Intro a Slack
- Intro a .git / GitHub. Armado de un repositorio y vinculación con Rstudio.


## Clase 2: Introducción (Pensar solo como repaso corto de contenido de materia previa?)
- Organización del flujo de trabajo (.Rproj, y git). 
  - Rutas. 
  - Buenas prácticas de la programación. 
- Reproducibilidad y Comunicación (.R y Rmd)
- La pipa de magrittr (%>%) para encadenar

## Clase 3: Domar los datos I

#### Los principales paquetes y sus verbos
- Lectura de datos (`{readr}`, `{heaven}`, `{readxl}`, `{googlesheets4}`)
- Limpieza de datos (`{dplyr}`, `{tidyr}`, `{janitor}`, `{tibble}`)


## Clase 4: Domar los datos II

#### Ampliando la caja de herramientas:
- `{glue}`: facilitar la concatenación.
- `{lubridate}`: tratamiento de fechas.
- `{forcats}`: tratamiento de datos categóricos.
- `{stringr}` tratamiento de datos de texto.


## Clase 5: Programación (intro)

#### No repetirse uno mismo
- Escribir funciones
- Programación funcional (Introducción a `{purrr}`)


## Clase6: Domar los datos III - Trabajar con geo data:
- `{sf}`
- `{rmapshaper}`
- `{geoAr}`


## Clase 7: Data Viz I - La Gramática de los Gráficos
- Introducción a `{ggplot2}`


## Clase 8: Data Viz II

####Las muchas capas de ggplot2
Extensiones: patchwork, cowplot , entre otros.

Clase 9: ????

    Podemos usar esta clase libre (en el orden que sea) para poner en práctica lo visto hasta x momento. O dejarla para el final para espacio de puesta en común sobre proyectos / avance grupal / Ejercitación / algo por el estilo.

Clase 10: Data Viz III
Distintas formas de representar información geográfica:
geom_sf(): para mapas estáticos mapsf
leaflet: para mapas interactivos
geofacet: para grillas como si fueran mapas
tilemaps: cuando el área no importa

Manual de clase https://tuqmano.github.io/geo_utdt/

**Comment by TuQmano** [comment]
Cierro con https://github.com/TuQmano/geo_utdt/commit/c8cf32de151f2245a142c02e35eb527aa2941ff4

- [X] Actualización del programa
- [X] Repo backup 2021 lineado en _Ediciones Anteriores_

Nuevo site publicado en https://tuqmano.github.io/geo_utdt/
